info:
  version: 1.0.0
  description: NSSF initial local configuration

configuration:
  nssfName: NSSF
  sbi:
    scheme: http
    registerIPv4: nssf
    bindIPv4: 0.0.0.0
    port: 8000
    name: nssf
  nrf:
    scheme: http
    IPv4Addr: nrf
    port: 8000
  serviceList:
    - serviceName: nnssf-nsselection
      version: 2.0.0
      scheme: http
      bindIPv4: 0.0.0.0
      port: 8000
  locality: area01
  mongodb:
    name: free5gc
    url: mongodb://admin:free5gc@db:27017
