info:
  version: 1.0.0
  description: PCF initial local configuration

configuration:
  pcfName: PCF
  sbi:
    scheme: http
    registerIPv4: pcf
    bindIPv4: 0.0.0.0
    port: 8000
    name: pcf
  nrf:
    scheme: http
    IPv4Addr: nrf
    port: 8000
  serviceList:
    - serviceName: npolicy-authorization
      version: 2.0.0
      scheme: http
      bindIPv4: 0.0.0.0
      port: 8000
  locality: area01
  mongodb:
    name: free5gc
    url: mongodb://admin:free5gc@db:27017
